# Generated by Django 4.1.13 on 2024-03-04 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_questionattempt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuestionAttempt",
        ),
    ]
